# frontend/Dockerfile
FROM node:20-slim

WORKDIR /app

# Copiamos los archivos de configuración primero
COPY package*.json ./

# Limpieza antes de instalar
RUN npm install

# Copiamos el resto del proyecto
COPY . .
# al final de tu Dockerfile
ENTRYPOINT ["sh","-c","npm run dev -- --host"]
