FROM node:23-alpine

WORKDIR /app
COPY package*.json ./

RUN npm install --save-dev ts-node-dev tsconfig-paths

RUN npm pkg set scripts.dev="ts-node-dev --respawn --transpile-only -r tsconfig-paths/register src/index.ts"

RUN npm install

COPY . .

CMD ["npx", "ts-node-dev", "--respawn", "--transpile-only", "-r", "tsconfig-paths/register", "src/index.ts"]