FROM node:23-bullseye

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY prisma ./prisma
COPY . .
RUN npx prisma generate
ENTRYPOINT ["sh","-c","npm install && npm run dev"]
#CMD ["npm", "run", "dev"]